### ISSUE TITLE
test issue for bridge (third headline)

### ISSUE THREAD

**Issue by okc-ok** [cdeadmin/cdetest#2]
Replace the current description in the issue and see whether the bridge adds the LTC bug # back.

<cde:info> Mirrored with LTC bug #147841</cde:info>

**Comment by okc-ok** [comment]
Add a comment; do not set the mirroring label just yet ...

**Comment by okc-ok** [comment]
Now the mirror label has been added; inspect the results.

**Comment by okc-ok** [comment]
Test the effect of removing the mirror label from the issue.

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;cdeadmin@us.ibm.com at 2017-06-26 11:50:10.&lt;cde:lastmodifiedby&gt;
Cancelled by the CDE Bridge because the corresponding problem was moved out of the bridge problem domain

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;carndt@us.ibm.com at 2017-06-26 15:50:46.&lt;cde:lastmodifiedby&gt;
------- Comment From carndt@us.ibm.com 2017-06-26 14:50:46 EDT-------
Confirm whether an internal-only comment is blocked from mirroring.

**Comment by okc-ok** [comment]
Nope ... filtering of internal-only comments will need to be fixed.

**Comment by okc-ok** [comment]
Test GitHub issue state change: CLOSED

**Comment by okc-ok** [comment]
Test GitHub issue state change: REOPENED

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;carndt@us.ibm.com at 2017-06-27 15:49:56.&lt;cde:lastmodifiedby&gt;
------- Comment From carndt@us.ibm.com 2017-06-27 14:49:56 EDT-------
Test LTC bug state change: REJECTED WILL_NOT_FIX

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;carndt@us.ibm.com at 2017-06-27 15:55:52.&lt;cde:lastmodifiedby&gt;
------- Comment From carndt@us.ibm.com 2017-06-27 14:55:52 EDT-------
Retest: LTC bug REJECTED

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;carndt@us.ibm.com at 2017-06-27 17:30:54.&lt;cde:lastmodifiedby&gt;
------- Comment From carndt@us.ibm.com 2017-06-27 16:30:54 EDT-------
Revised the LTC and GitHub state mappings ... try REJECTED again!

**Comment by okc-ok** [comment]
Good ... this time the issue was closed.
