### ISSUE TITLE
Test mirroring bug to GitHub issue

### ISSUE THREAD

**Issue by cdeadmin** [cdeadmin/cdetest#3]
<cde:info> Mirrored with LTC bug #147843 </cde:info>

**Comment by cdeadmin** [comment]
&lt;cde:lastmodifiedby&gt;carndt@us.ibm.com at 2017-06-27 17:47:57.&lt;cde:lastmodifiedby&gt;
------- Comment From carndt@us.ibm.com 2017-06-27 16:47:56 EDT-------
This is a test to see whether a new bug can be mirrored to a GitHub issue.

Just testing ...

**Comment by okc-ok** [comment]
Ping back to the bug to see if the description gets posted.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-28 14:02:12 EDT-------
Making some adjustments to see whether the blank comment headers can be prevented.

Status = ASSIGNED

**Comment by okc-ok** [comment]
Test comment from GitHub ...

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-28 16:45:47 EDT-------
Test comment back from Bugzilla ...

Status = DEFERRED

**Comment by okc-ok** [comment]
Another test comment from GitHub ...

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-28 16:54:54 EDT-------
... and another test comment from Bugzilla.

Status = REJECTED

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-29 09:31:52 EDT-------
Testing for exclusion of comment headers attributed to the bridge userid.

Status = REOPENED

**Comment by okc-ok** [comment]
Status changes appear to be working well at this time. Remember to check for special status values which require setting (or clearing) labels on the issue.

**Comment by okc-ok** [comment]
Check behavior of the bridge.timezone property.
May experience replicated comment headers in the bug.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-29 14:28:03 EDT-------
Replicated comment headers were confirmed.
Probably time for a new test bug.

**Comment by okc-ok** [comment]
To confirm: I did not see an internal-only comment appear in the GitHub issue.
Oh, what happens with **bold** and _italicized_ text?

**Comment by okc-ok** [comment]
Add some labels to the issue for testing.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-29 16:53:08 EDT-------
What happens if I remove the help_wanted tag from the bug?

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-29 16:55:45 EDT-------
heh ... the tag reappeared in the bug. Try again after changing the issue modify action.

**Comment by okc-ok** [comment]
Sweet ... the "help wanted" label was removed from the issue.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 11:21:06 EDT-------
Test what happens if I add a bogus label to the whiteboard.

**Comment by okc-ok** [comment]
Confirmed ... I see that the bogus label was not applied to the issue, and it was removed from the bug afterward.

**Comment by cdeadmin** [comment]
Cancelled by the CDE Bridge because the corresponding problem was moved out of the bridge problem domain

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 14:04:26 EDT-------
Just to verify that mirroring is still active after changing the routings.
