### ISSUE TITLE
Issue for testing the investigators

### ISSUE THREAD

**Issue by okc-ok** [cdeadmin/cdetest#4]
Initially this issue will have no labels and will not be eligible for mirroring.

<cde:info> Mirrored with LTC bug #147844 </cde:info>

**Comment by okc-ok** [comment]
Add a non-mirroring label for testing.

**Comment by okc-ok** [comment]
... and now add a valid mirroring label.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 14:10:22 EDT-------
Prepare for reroute to a different component.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 14:13:20 EDT-------
Change from the Host component to the Performance component.

**Comment by okc-ok** [comment]
Removing the mirror label from the issue.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 14:35:32 EDT-------
Another reroute of the bug to the security component.

Status = NEEDINFO

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-06-30 14:38:21 EDT-------
Leaving the HostOS product ... going to the OPAL product

Status = REJECTED

**Comment by okc-ok** [comment]
Appears to be behaving as expected ... no unexpected changes to either the issue or the bug.
