### ISSUE TITLE
Testing mirroring of initial description

### ISSUE THREAD

**Issue by okc-ok** [cdeadmin/cdetest#6]
This is the initial issue description.
Observe how it behaves when mirrored to Bugzilla.
Multiple lines to test the behavior.

*** Curious ... what happens when the issue's description is edited?  ***

<cde:info> Mirrored with LTC bug #147873 </cde:info>

**Comment by okc-ok** [comment]
Post a second comment to the issue for mirror testing.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-12 09:20:16 EDT-------
Write a comment in the bug for mirroring back to the GitHub issue.
See whether we can make use of the bug's description field.

**Comment by okc-ok** [comment]
Closing this issue; will continue testing with a new issue.
